#release configuration
#Thu Dec 21 19:37:10 CET 2023
projectVersionPolicyId=default
project.rel.io.github.epi155\:recfm-maven-plugin=0.7.1
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
project.scm.io.github.epi155\:recfm-maven-plugin.connection=scm\:git\:git\://github.com/epi155/recfm-maven-plugin.git
project.scm.io.github.epi155\:recfm-maven-plugin.url=https\://github.com/epi155/recfm-maven-plugin.git
project.dev.io.github.epi155\:recfm-maven-plugin=0.7.1-SNAPSHOT
completedPhase=run-completion-goals
scm.url=scm\:git\:https\://github.com/epi155/recfm-maven-plugin.git
project.scm.io.github.epi155\:recfm-maven-plugin.developerConnection=scm\:git\:https\://github.com/epi155/recfm-maven-plugin.git
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
scm.tag=recfm-maven-plugin-0.7.1
project.scm.io.github.epi155\:recfm-maven-plugin.tag=recfm-maven-plugin-0.7.0
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
